export const HOVER_FILL_COLOR = "#22d3ee";
export const HOVER_EDGE_COLOR = "#14b8a6";

export const BUILDING_HIGHLIGHT_FILL = "#0ea5e9";
export const BUILDING_HIGHLIGHT_EDGE_PRIMARY = "#38bdf8";
export const BUILDING_HIGHLIGHT_EDGE_SECONDARY = "#22d3ee";
export const BUILDING_HIGHLIGHT_EMISSIVE = "#22d3ee";
export const BUILDING_HIGHLIGHT_EMISSIVE_INTENSITY = 0.8;
export const BUILDING_SELECTED_FILL = "#facc15";
export const BUILDING_SELECTED_EDGE_PRIMARY = "#f97316";
export const BUILDING_SELECTED_EDGE_SECONDARY = "#f97316";
export const BUILDING_SELECTED_EMISSIVE = "#f97316";
export const BUILDING_SELECTED_EMISSIVE_INTENSITY = 0.65;
