import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import UnifiedHeader from "../components/unified-header";
import ClientProviders from "@/providers/client-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
  variable: "--font-app-sans",
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500"],
  variable: "--font-app-mono",
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      {process.env.NODE_ENV === "development" && (
        <head>
          {/*
            DevTools extension can crash when it encounters an empty renderer
            version string. Inject a tiny development-only guard early to
            normalize any renderer.version to a safe semver string so the
            extension's semver parser won't throw. This preserves DevTools
            functionality while avoiding console noise during development.
          */}
          <script
            dangerouslySetInnerHTML={{
              __html: `(() => {
                try {
                  if (typeof window === 'undefined') return;
                  const hook = window.__REACT_DEVTOOLS_GLOBAL_HOOK__;
                  if (!hook) return;
                  // Wrap the inject function so renderer objects get a safe version
                  const originalInject = hook.inject;
                  if (originalInject && !originalInject.__wrapped_for_version_guard__) {
                    hook.inject = function(renderer) {
                      try {
                        if (renderer && (renderer.version === '' || renderer.version == null)) {
                          // assign a safe default semver so semver.parse won't throw
                          renderer.version = '0.0.0';
                        }
                      } catch (e) {
                        // swallow any errors here; we don't want to break the app
                      }
                      return originalInject.apply(this, arguments);
                    };
                    hook.inject.__wrapped_for_version_guard__ = true;
                  }
                } catch (e) {}
              })();`,
            }}
          />
        </head>
      )}
        <body
          className={`${plexSans.variable} ${plexMono.variable} antialiased min-h-screen flex flex-col bg-background text-foreground`}
        >
            <ClientProviders>
              <UnifiedHeader />
              <main className="flex-1 min-h-0 overflow-hidden">{children}</main>
              {/* <Footer /> */}
            </ClientProviders>
        </body>
    </html>
  );
}

export default RootLayout;
